name: Update with activity

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: g0621/github-activity@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}