name: Update with activity

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: g0621/github-activity@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          MAX_LINES: 5
